Change initializers to object instances
If callables are passed as initializers, the resulting model cannot be saved. Minimal repro:

```python
M = tf.keras.Sequential([tf.keras.layers.Dense(1, kernel_initializer=tf.initializers.zeros)])
M.build([2,1])
M.save('test_model')
```
[...blah...]
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/initializers/__init__.py", line 135, in serialize
    return generic_utils.serialize_keras_object(initializer)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 245, in serialize_keras_object
    config = instance.get_config()
TypeError: get_config() missing 1 required positional argument: 'self'

I'm guessing the initializer still works if passed as a callable. Nevertheless, passing a callable should probably be an error, *or* saving it should result in a human-readable error.

Independent of the real fix, the tutorials should not include such questionable use.