Fix bug: call tf.random.set_random_seed instead of tf.random.set_seed
tf.random.set_seed(13) produces 

AttributeError: module 'tensorflow._api.v1.random' has no attribute 'set_seed'

In new versions of Tensorflow this is renamed to

tf.random.set_random_seed(13)