Update source.md
I believe --config=opt not supported command.Getting the below error.
ERROR: Config value 'opt' is not defined in any .rc file
Hence proposing to remove this option from the example code above.