Fix package resolution for sngp guide.
When `pip install tensorflow` resolves to 2.6 (e.g. public colab) then
everything works fine. However when it installs tensorflow 2.7, the legacy
resolver isn't smart enough to downgrade TF back down to resolve the version
conflict.

```
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
tensorflow-metadata 1.4.0 requires absl-py<0.13,>=0.9, but you'll have absl-py 0.15.0 which is incompatible.
tensorflow-text 2.6.0 requires tensorflow<2.7,>=2.6.0, but you'll have tensorflow 2.7.0 which is incompatible.
```

Using the modern resolver gets 2.6 installed, but pip seems to prefer the path of least resistance (fewest package changes), so after installing `tensorflow-2.7.0`, downgrading via `tf-models-official` picks `tensorflow-2.6.0`, as it already has `keras-2.7.0`, `tensorflow-estimator-2.7.0`, etc.

To get around this, I've blocked `tensorflow-2.6.0` via a pip constraint. These two changes slow the pip resolution down a lot, but it works.

PiperOrigin-RevId: 408763953